#' Load list of field tables and names to be pulled from SOS's API
#'
#' @return list of character vectors
#' @export
#'
#' @examples
#' table_fields()[1]
table_fields <- function(){
  list("participant_sessions"=c("participants_id","sessions_id","organizations_id","sessions_groups_id","dob","gradeLevelInSchool","numberOfServiceDays","totalDays","totalFFS","endOfSeason","calc_high_risk","pre","participantNeeds","strengths_academicGoals","strengths_activityEngagement","strengths_adultDrugUse","strengths_adultPrison","strengths_anger","strengths_arguments","strengths_behaviorProblems","strengths_bully","strengths_challenges","strengths_difficultyFocusing","strengths_drugUse","strengths_englishSecondLang","strengths_freeReducedLunch","strengths_friendsDrugs","strengths_friendships","strengths_indCompleting","strengths_juvie","strengths_learningDisability","strengths_lives","strengths_mentalHealth","strengths_physicalActivity","strengths_positiveSelfEsteem","strengths_schoolInterest","strengths_victimBullying","strengths_other,updatedDate"),
       "participants" = c("civiCoreParticipantID","lastName","firstName","dateOfBirth","age","gender","ethnicity","numberOfAdultsInHousehold","annualFamilyIncome","highSchoolGraduate","updatedDate"),
       "sessions" = c("sessionName","sessionStartDate","sessionType","programType","region","programLocation","mountainResort","mountainResort","sessionYear","applicationType"),
       "university_responses" = c("participants_id","sessions_id","surveyType","enteredDate","updatedDate","calc_enteredDate","yearInSOSUniversity","location","season","grade","acadIntent1I","acadIntent2J","activity1","activity2","activity3","comEngage1","comEngage2","comEngage3","comSkill1","comSkill2","comSkill3","comSkill4","comSkillx","control1","control2","control3","control4","control5","control6","control7","control8","decisionMak1","decisionMak2","decisionMak3","decisionMak4","decisionMak5","decisionMak6","decisionMak7","decisionMak8","diverse1","diverse2","diverse3","diverse4","diverse5","diverse6","diverse7","diverse8","diverse9","diverse10","diverse11","drugAlc1","drugAlc2","drugAlc3","drugAlc4","drugAlc5","drugAlc6","drugAlc7","drugAlc8","drugAlc9","drugAlc10","drugAlc11","drugAlc12","eATQActiv1R","eATQActiv2","eATQActiv3","eATQAtten1","eATQAtten2R","eATQAtten3","eATQFrust1","eATQFrust2","eATQFrust3","eATQInhib1R","eATQInhib2","eATQInhib3R","education1a","education1b","education1c","education1d","education1e","education2a","education2b","education2c","education2d","education2e","exper1","exper2","exper3","exper4","exper5","exper6","exper7","exper8","exper9","exper10","exper11","exper12","futureOr1","futureOr2","futureOr3","futureOr4","goalS1","goalS2","goalS3","goalS4","goalS5","health1","health2","health3","health4","health4b","health5","health6","health7","health8","jSkills1","jSkills2","jSkills3","jSkills4","jSkills5","jSkills6","leadership1","leadership2","leadership3","leadership4","leadership5","mentor1","mentor2","mentor3","mentor4","mentor5","misc1","misc2","parents","proSoc1","proSoc2","proSoc3","proSoc4","selfEff1","selfEff2","selfEff3","selfEff4","selfEff5","selfEff6","selfEst1","selfEst2","selfEst3","selfEst4","selfEst5","selfEst6","selfEst7","selfEst8","selfEst9","selfReg1","selfReg2","selfReg3","selfReg4","selfReg5","selfReg6","selfReg7")
  )
}
